# Generated by Django 3.0.6 on 2020-05-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeNum', models.IntegerField(verbose_name='员工编号')),
                ('EmployeeName', models.CharField(max_length=20, verbose_name='姓名')),
                ('StaffNum', models.IntegerField(verbose_name='领导编号')),
                ('DepartmentNum', models.IntegerField(verbose_name='部门编号')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applidate', models.DateTimeField(auto_now_add=True, verbose_name='请假日期')),
                ('EmployeeNum', models.IntegerField(verbose_name='员工编号')),
                ('AppliType', models.IntegerField(verbose_name='请假类型')),
                ('BeginTime', models.DateField(verbose_name='开始日期')),
                ('EndTime', models.DateField(verbose_name='结束日期')),
                ('Days', models.IntegerField(verbose_name='累计天数')),
                ('Reason', models.CharField(max_length=500, verbose_name='请假原因')),
                ('ConfirmLogo', models.CharField(max_length=5, verbose_name='确认标志')),
                ('ConfirmName', models.CharField(max_length=20, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '请假',
                'verbose_name_plural': '请假',
            },
        ),
    ]
