# Generated by Django 3.0.6 on 2020-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('EmployeeNum', models.IntegerField(verbose_name='员工编号')),
                ('Password', models.CharField(max_length=16, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '注册',
                'verbose_name_plural': '注册',
            },
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='Applidate',
            field=models.DateTimeField(verbose_name='请假日期'),
        ),
    ]
