# Generated by Django 3.0.6 on 2020-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20200531_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='AppliType',
            field=models.CharField(max_length=10, verbose_name='请假类型'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='ConfirmLogo',
            field=models.CharField(max_length=5, null=True, verbose_name='确认标志'),
        ),
    ]
