# Generated by Django 3.0.6 on 2020-06-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20200602_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='Employ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.Register'),
            preserve_default=False,
        ),
    ]
