# Generated by Django 3.0.6 on 2020-06-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_leaveapplication_employ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='Empname',
        ),
    ]
