# Generated by Django 3.0.6 on 2020-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_userprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='UserType',
            field=models.CharField(max_length=10, verbose_name='用户类型'),
        ),
    ]
