# Generated by Django 3.0.6 on 2020-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_auto_20200603_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='Employ',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='EmployeeNum',
            field=models.IntegerField(default=2017040349, verbose_name='员工编号'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
