# Generated by Django 3.0.6 on 2020-06-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20200603_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='Em',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.UserProfil'),
            preserve_default=False,
        ),
    ]
