# Generated by Django 3.0.6 on 2020-06-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_leaveapplication_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='employ',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.UserProfil'),
            preserve_default=False,
        ),
    ]
