# Generated by Django 3.0.6 on 2020-06-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_delete_managers'),
        ('Employee', '0011_userprofil_departms'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='mde',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.DepartMent'),
            preserve_default=False,
        ),
    ]
