# Generated by Django 3.0.6 on 2020-06-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_employeeinfo_mde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='DepartmentNum',
            field=models.CharField(max_length=10, verbose_name='部门'),
        ),
    ]
