# Generated by Django 3.1.2 on 2021-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=11, verbose_name='姓名')),
                ('IsolationSign', models.CharField(max_length=11, verbose_name='隔离标志')),
            ],
            options={
                'verbose_name': '隔离信息',
                'verbose_name_plural': '隔离信息',
            },
        ),
    ]
