# Generated by Django 3.1.2 on 2021-01-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=11, verbose_name='物品名称')),
                ('Acount', models.IntegerField(max_length=11, verbose_name='数量')),
            ],
            options={
                'verbose_name': '物品名称',
                'verbose_name_plural': '物品名称',
            },
        ),
    ]
