# Generated by Django 3.1.2 on 2021-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Acount',
            field=models.FloatField(max_length=11, verbose_name='数量'),
        ),
    ]
