# Generated by Django 3.1.2 on 2021-01-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20210111_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InfoName', models.CharField(max_length=100, verbose_name='信息名称')),
                ('InfoLink', models.CharField(max_length=100, verbose_name='信息链接')),
                ('InfoDate', models.CharField(max_length=20, verbose_name='信息时间')),
            ],
            options={
                'verbose_name': '疫情信息',
                'verbose_name_plural': '疫情信息',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyName', models.CharField(max_length=100, verbose_name='政策名称')),
                ('PolicyLink', models.CharField(max_length=100, verbose_name='政策链接')),
                ('PolicyDate', models.CharField(max_length=20, verbose_name='政策时间')),
            ],
            options={
                'verbose_name': '疫情政策',
                'verbose_name_plural': '疫情政策',
            },
        ),
    ]
