# Generated by Django 3.1.2 on 2021-01-04 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(max_length=10, verbose_name='用户类型')),
                ('Name', models.CharField(max_length=11, verbose_name='姓名')),
                ('IdCard', models.CharField(max_length=20, verbose_name='身份证号')),
                ('Phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('UnitNumber', models.IntegerField(verbose_name='单元号')),
                ('FloorNumber', models.IntegerField(verbose_name='楼号')),
                ('HouseNumber', models.IntegerField(verbose_name='房间号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户注册',
                'verbose_name_plural': '用户注册',
            },
        ),
    ]
