# Generated by Django 3.1.2 on 2021-01-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRepords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataReport', models.DateField(verbose_name='填报日期')),
                ('Temperature', models.IntegerField(verbose_name='体温')),
                ('Isolated', models.IntegerField(verbose_name='是否隔离')),
                ('Cough', models.IntegerField(verbose_name='咳嗽')),
                ('Other', models.CharField(max_length=100, verbose_name='其他')),
                ('DayRepord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resident.userprofil')),
            ],
            options={
                'verbose_name': '每日上报',
                'verbose_name_plural': '每日上报',
            },
        ),
    ]
