# Generated by Django 3.1.2 on 2021-01-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='Is',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.isolation'),
        ),
    ]
