# Generated by Django 3.1.2 on 2021-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_auto_20210111_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinto',
            name='IntoSign',
            field=models.CharField(max_length=11, null=True, verbose_name='审核结果'),
        ),
        migrations.AddField(
            model_name='getout',
            name='OutSign',
            field=models.CharField(max_length=11, null=True, verbose_name='审核结果'),
        ),
    ]
