# Generated by Django 3.1.2 on 2021-01-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_dailyrepords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrepords',
            name='Cough',
            field=models.IntegerField(max_length=11, verbose_name='咳嗽'),
        ),
        migrations.AlterField(
            model_name='dailyrepords',
            name='DataReport',
            field=models.DateField(max_length=11, verbose_name='填报日期'),
        ),
        migrations.AlterField(
            model_name='dailyrepords',
            name='Isolated',
            field=models.IntegerField(max_length=11, verbose_name='是否隔离'),
        ),
        migrations.AlterField(
            model_name='dailyrepords',
            name='Temperature',
            field=models.IntegerField(max_length=11, verbose_name='体温'),
        ),
    ]
