# Generated by Django 3.1.2 on 2021-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='Place',
            field=models.CharField(max_length=100, null=True, verbose_name='住址'),
        ),
    ]
