# Generated by Django 3.1.2 on 2021-01-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_auto_20210104_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrepords',
            name='Cough',
            field=models.CharField(max_length=11, verbose_name='咳嗽'),
        ),
        migrations.AlterField(
            model_name='dailyrepords',
            name='Isolated',
            field=models.CharField(max_length=11, verbose_name='是否隔离'),
        ),
        migrations.AlterField(
            model_name='dailyrepords',
            name='Temperature',
            field=models.FloatField(max_length=11, verbose_name='体温'),
        ),
    ]
