# Generated by Django 3.1.2 on 2021-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_help_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='Place',
            field=models.CharField(max_length=100, verbose_name='住址'),
        ),
    ]
