# Generated by Django 3.1.2 on 2021-01-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_auto_20210104_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrepords',
            name='DayRepord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resident.userprofil'),
        ),
    ]
