# Generated by Django 3.1.2 on 2021-01-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_auto_20210104_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataApply', models.DateField(max_length=11, verbose_name='申请日期')),
                ('Destination', models.CharField(max_length=11, verbose_name='目的地')),
                ('OutReason', models.CharField(max_length=11, verbose_name='原因')),
                ('GOut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resident.userprofil')),
            ],
            options={
                'verbose_name': '出社区申请',
                'verbose_name_plural': '出社区申请',
            },
        ),
        migrations.CreateModel(
            name='GetInto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInto', models.DateField(max_length=11, verbose_name='日期')),
                ('MainDes', models.CharField(max_length=11, verbose_name='停留地点')),
                ('Travel', models.CharField(max_length=11, verbose_name='重点地区')),
                ('Places', models.CharField(max_length=100, verbose_name='途径地')),
                ('Gin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resident.userprofil')),
            ],
            options={
                'verbose_name': '进社区申请',
                'verbose_name_plural': '进社区申请',
            },
        ),
    ]
