# Generated by Django 3.1.2 on 2021-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0006_getinto_getout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='FloorNumber',
            field=models.IntegerField(null=True, verbose_name='楼号'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='HouseNumber',
            field=models.IntegerField(null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='UnitNumber',
            field=models.IntegerField(null=True, verbose_name='单元号'),
        ),
    ]
