# Generated by Django 3.1.2 on 2021-01-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0007_auto_20210106_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='FloorNumber',
            field=models.CharField(max_length=11, null=True, verbose_name='楼号'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='HouseNumber',
            field=models.CharField(max_length=11, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='UnitNumber',
            field=models.CharField(max_length=11, null=True, verbose_name='单元号'),
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datahelp', models.DateField(max_length=11, verbose_name='日期')),
                ('HelpType', models.CharField(max_length=11, verbose_name='帮助类型')),
                ('Details', models.CharField(max_length=100, verbose_name='详细介绍')),
                ('ResPerson', models.CharField(max_length=11, null=True, verbose_name='负责人')),
                ('HelpSign', models.CharField(max_length=11, null=True, verbose_name='接受标志')),
                ('Helps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resident.userprofil')),
            ],
            options={
                'verbose_name': '互助申请',
                'verbose_name_plural': '互助申请',
            },
        ),
    ]
