# Generated by Django 3.1.2 on 2021-01-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0007_auto_20210106_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='FloorNumber',
            field=models.CharField(max_length=11, null=True, verbose_name='楼号'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='HouseNumber',
            field=models.CharField(max_length=11, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='UnitNumber',
            field=models.CharField(max_length=11, null=True, verbose_name='单元号'),
        ),
    ]
