# Generated by Django 3.1.2 on 2021-01-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0009_dailyuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuse',
            name='UseSign',
            field=models.CharField(max_length=11, null=True, verbose_name='查看标志'),
        ),
        migrations.AlterField(
            model_name='dailyuse',
            name='UseType',
            field=models.CharField(max_length=100, verbose_name='用品名称'),
        ),
    ]
