# Generated by Django 3.0.6 on 2020-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartMentNum', models.IntegerField(verbose_name='部门编号')),
                ('DepartMentName', models.CharField(max_length=20, verbose_name='部门名称')),
                ('DepartMentSir', models.CharField(max_length=20, verbose_name='部门管理员')),
                ('DepartMentStaffNum', models.IntegerField(verbose_name='管理员编号')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
            },
        ),
    ]
