# Generated by Django 3.0.6 on 2020-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mauser_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('mapassword', models.CharField(max_length=16, verbose_name='密码')),
                ('maemail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('maphone', models.EmailField(max_length=11, verbose_name='手机号')),
                ('maadd_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '部门管理员注册表',
                'verbose_name_plural': '部门管理员注册表',
            },
        ),
    ]
