# Generated by Django 3.0.6 on 2020-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20200531_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='maphone',
            field=models.IntegerField(max_length=11, verbose_name='手机号'),
        ),
    ]
