# Generated by Django 3.0.6 on 2020-06-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20200531_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='managers',
        ),
    ]
